### ISSUE TITLE
Since latest Monarch update, failed setup

### ISSUE THREAD

**Issue by guy0nabuffalo** [sanghviharshit/ha-monarchmoney#5]
Since updating to the latest version of Monarch, I am getting a failed setup error. 
Error communicating with API: 'MonarchMoney' object has no attribute 'get_cashflow'.

I've tried competely removing the integration and adding it back (restarting HA after removing and re-installing) but still getting the error message.

![image](https://github.com/sanghviharshit/ha-monarchmoney/assets/42823584/23e342d5-c5ac-4103-9e79-d2486f2a9a96)

**Comment by guy0nabuffalo** [comment]
I was on the 0.0.2 branch. I also tried the main branch but had the same error. Switched back to 0.0.1 and Monarch is working again.

**Comment by jerry-knight** [comment]
I'm not a developer (python, home assistant, or otherwise) but I tried tracking down the referenced error. It's in `update_coordinator.py line 109-110`. Commenting those out and retrying worked for me. Obviously the cashflow sensor is now "unknown" but everything else seems to be working.

**Comment by Blitzzz13** [comment]
I am also a first time user here (had Mint, now loving Monarch Money), however I also failed the login. However, similar to above, commenting out the lines as mentioned above solved the problem. Unfortunately those are the data points I want to incorporate into HA. But appreciate the work and effort nonetheless.

**Comment by sanghviharshit** [comment]
This is now fixed in 0.0.3
